import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import Providers from "@/components/Providers";

import "react-loading-skeleton/dist/skeleton.css"
import "simplebar-react/dist/simplebar.min.css"
import { Toaster } from "@/components/ui/toaster";


export const metadata: Metadata = {
   title: "CHAD AI",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en" className="light">
         <Providers>
            <body
               className={cn('min-h-screen font-sans antialiased grainy')}
            //   className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
               <Toaster />
               <Navbar />
               {children}
            </body>
         </Providers>
      </html>
   );
}
